In [33]:
import pandas as pd

df=pd.read_csv(r'C:\Users\k9481\OneDrive\Documents\ml databases\WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [34]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [36]:
df.shape

(7043, 21)

In [37]:
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [38]:
# No     5174   ← 73%
# Yes    1869   ← 27%
# Imbalanced again — but worse than diabetes this time.

In [39]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [41]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [42]:
# Only 11 nulls in TotalCharges — drop those rows
df.dropna(inplace=True)

# Drop CustomerID — useless for prediction
df.drop(columns=['customerID'], inplace=True)

In [43]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [44]:
df.shape

(7032, 20)

In [45]:
# Binary columns — direct map
df['gender']         = df['gender'].map({'Male': 0, 'Female': 1})
df['Partner']        = df['Partner'].map({'Yes': 1, 'No': 0})
df['Dependents']     = df['Dependents'].map({'Yes': 1, 'No': 0})
df['PhoneService']   = df['PhoneService'].map({'Yes': 1, 'No': 0})
df['PaperlessBilling'] = df['PaperlessBilling'].map({'Yes': 1, 'No': 0})

# Target column
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

# Multi-value columns — use get_dummies (One Hot Encoding)
multi_cols = ['MultipleLines', 'InternetService', 'OnlineSecurity',
              'OnlineBackup', 'DeviceProtection', 'TechSupport',
              'StreamingTV', 'StreamingMovies', 'Contract',
              'PaymentMethod']

df = pd.get_dummies(df, columns=multi_cols, drop_first=True)

In [46]:
print(df.shape)   # columns will increase due to one-hot encoding

(7032, 31)

In [47]:
print(df.head())

   gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       1              0        1           0       1             0
1       0              0        0           0      34             1
2       0              0        0           0       2             1
3       0              0        0           0      45             0
4       1              0        0           0       2             1

   PaperlessBilling  MonthlyCharges  TotalCharges  Churn  ...  \
0                 1           29.85         29.85      0  ...
1                 0           56.95       1889.50      0  ...
2                 1           53.85        108.15      1  ...
3                 0           42.30       1840.75      0  ...
4                 1           70.70        151.65      1  ...

   TechSupport_Yes  StreamingTV_No internet service  StreamingTV_Yes  \
0            False                            False            False
1            False                            False            False
2            False                            False            False
3             True                            False            False
4            False                            False            False

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                False                False
1                                False                False
2                                False                False
3                                False                False
4                                False                False

   Contract_One year  Contract_Two year  \
0              False              False
1               True              False
2              False              False
3               True              False
4              False              False

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True
1                                  False                           False
2                                  False                           False
3                                  False                           False
4                                  False                            True

   PaymentMethod_Mailed check
0                       False
1                        True
2                        True
3                       False
4                       False

[5 rows x 31 columns]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   PaperlessBilling                       7032 non-null   int64
 7   MonthlyCharges                         7032 non-null   float64
 8   TotalCharges                           7032 non-null   float64
 9   Churn                                  7032 non-null   int64
 10  MultipleLines_No phone service         7032 non-null   bool
 11  MultipleLines_Yes                      7032 non-null   bool
 12  InternetService_Fiber optic            7032 non-null   bool
 13  InternetService_No                     7032 non-null   bool
 14  OnlineSecurity_No internet service     7032 non-null   bool
 15  OnlineSecurity_Yes                     7032 non-null   bool
 16  OnlineBackup_No internet service       7032 non-null   bool
 17  OnlineBackup_Yes                       7032 non-null   bool
 18  DeviceProtection_No internet service   7032 non-null   bool
 19  DeviceProtection_Yes                   7032 non-null   bool
 20  TechSupport_No internet service        7032 non-null   bool
 21  TechSupport_Yes                        7032 non-null   bool
 22  StreamingTV_No internet service        7032 non-null   bool
 23  StreamingTV_Yes                        7032 non-null   bool
 24  StreamingMovies_No internet service    7032 non-null   bool
 25  StreamingMovies_Yes                    7032 non-null   bool
 26  Contract_One year                      7032 non-null   bool
 27  Contract_Two year                      7032 non-null   bool
 28  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 29  PaymentMethod_Electronic check         7032 non-null   bool
 30  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(21), float64(2), int64(8)
memory usage: 748.5 KB

In [49]:
print(df['Churn'].unique())
print(df['Churn'].value_counts(dropna=False))

[0 1]
Churn
0    5163
1    1869
Name: count, dtype: int64

In [50]:
# After all your mapping and encoding, add this:
df.dropna(subset=['Churn'], inplace=True)

# Then reset index
df.reset_index(drop=True, inplace=True)

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [52]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,1,0,1,29.85,29.85,0,...,False,False,False,False,False,False,False,False,True,False
1,0,0,0,0,34,1,0,56.95,1889.50,0,...,False,False,False,False,False,True,False,False,False,True
2,0,0,0,0,2,1,1,53.85,108.15,1,...,False,False,False,False,False,False,False,False,False,True
3,0,0,0,0,45,0,0,42.30,1840.75,0,...,True,False,False,False,False,True,False,False,False,False
4,1,0,0,0,2,1,1,70.70,151.65,1,...,False,False,False,False,False,False,False,False,True,False

In [53]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [54]:
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix, log_loss, roc_auc_score)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob[:, 1]))
print("Log Loss :", log_loss(y_test, y_prob))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy : 0.7263681592039801
ROC-AUC  : 0.8349765233911922
Log Loss : 0.5090217253052643

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.49      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407


Confusion Matrix:
 [[724 309]
 [ 76 298]]

In [55]:
#  The New Skill: Threshold Tuning for Business
# This is what makes Project 3 special. Think like a business:

# Missing a customer who churns = company loses money
# So we want high Recall on churn class — catch as many churners as possible

# Try different thresholds and compare
thresholds = [0.3, 0.4, 0.5, 0.6]

for t in thresholds:
    y_pred_t = (y_prob[:, 1] >= t).astype(int)
    from sklearn.metrics import recall_score, precision_score
    r = recall_score(y_test, y_pred_t)
    p = precision_score(y_test, y_pred_t)
    print(f"Threshold {t} → Precision: {p:.2f}  Recall: {r:.2f}")

Threshold 0.3 → Precision: 0.41  Recall: 0.93
Threshold 0.4 → Precision: 0.45  Recall: 0.87
Threshold 0.5 → Precision: 0.49  Recall: 0.80
Threshold 0.6 → Precision: 0.54  Recall: 0.72

In [56]:
feature_names = X.columns.tolist()
importance = pd.Series(model.coef_[0], index=feature_names)
top_features = importance.abs().sort_values(ascending=False).head(10)
print(top_features)

tenure                            1.263854
MonthlyCharges                    0.928682
InternetService_Fiber optic       0.746144
Contract_Two year                 0.638598
TotalCharges                      0.623279
Contract_One year                 0.326693
StreamingTV_Yes                   0.259691
StreamingMovies_Yes               0.252870
MultipleLines_Yes                 0.202763
PaymentMethod_Electronic check    0.193697
dtype: float64

In [57]:
# Create a sample customer matching your encoded columns
sample = X.iloc[0:1].copy()   # take first row as template
sample_scaled = scaler.transform(sample)

result = model.predict(sample_scaled)
prob   = model.predict_proba(sample_scaled)

print("Will Churn?  :", "Yes" if result[0] == 1 else "No")
print("Probability  :", round(prob[0][1] * 100, 2), "%")

Will Churn?  : Yes
Probability  : 81.06 %